### ISSUE TITLE
[Улучшение] Скины

### ISSUE THREAD

**Issue by KamariON-wkv** [NeotenySS/MineAge#1]
**Где хотите осуществить идею? (Сайт, сервер, лаунчер, донат магазин, дискорд)**
В лаунчере

**Подробное описание идеи**
Сделать функцию по добавлению скинов в лаунчере и привязкой к аккаунту.

**Ваш ник в игре и в дискорде**
kybik_1da

**Опишите как это может улучшить проект**
Возможность поставить свой скин, сделать своего рода индивидуальность персонажа и добавить разнообразие персонажей на сервере.

**!Не удалять текст ниже!**
Я оформил текст правильно и дал максимально подробную информацию. Я оставляю право за разработчиком или владельцем проекта согласиться на моё предложение или отказаться от него, в обоих случаях я не имею претензий к проекту и его руководящему составу. Я не претендую на идею в случае внедрения и отдаю права пользования проекту. В случае изменения данного текста или его удаления, разработчик или владелец проекта имеет полное право закрыть тикет без объяснения причин.

**Comment by NeotenySS** [comment]
> Опишите как это может улучшить проект
> Возможность поставить свой скин на сервере улучшить визуально сервер

Не подробно описано

> Опишите как это может улучшить проект
> Возможность поставить свой скин на сервере улучшить визуально сервер

За визуальную часть отвечает концепция майнкрафта, текстур паки (но у нас они отсутствуют) и шейдеры для улучшения визуализации.

Сомнительное предложение, причём делать это на сайте.....

**Comment by RudyWadeBoom** [comment]
@NeotenySS а какое требуется описание? Чтобы он указал каждую деталь создания скрипта по загрузке и пошагово описал как осуществить это? 
Если нужна подробная описание, то: реализовать загрузку скина на сайте через добавления отображения скина в профиле, конпка которая отвечает затзагрущкк скина, кнопка которая отвечает за отправку скина на сервер, где он будет хранится, сделать привязку скина к нику игрока или UUID.
Открывай запрос, давай обсудим.

**Comment by NeotenySS** [comment]
@RudyWadeBoom загрузчик использует автоматическое переименование, он не присвоит ему ник игрока, это можно сделать если переписать почти половину php на сайте. По сути это не имеет смысла, игроки пользуются сайтом только для просмотра информации по обновлению, проверки цен или покупке в донат магаизне (а он кстати ещё не доработан), нужно сделать привязку к карте сервера и разместить его, это большой объём + мы подготавливаем сервер к запуску.
Не имеет эффективности добавление скина через сайт, как и толк на сервере, если игрокам он присваивается рандомно.

**Comment by RudyWadeBoom** [comment]
@NeotenySS ок, давай реализуем загрузку скина через сам сервер, путём стороннего плагина, м? На худой конец

**Comment by NeotenySS** [comment]
@RudyWadeBoom Это лишняя нагрузка на сервер, я знаю о каком плагине идёт речь, он постоянно должен проверять uuid игрока чтобы скин держался на игроке, да и в случае мелкого сбоя на серверах где хранятся скины во время работы этого плагина, то слетят скины у всех игроков, и что тогда? каждый раз доставлять этот дискомфорт чтобы игроки просто скин нацепили, какой какой-либо важной необходимости? а потом запросы полетят что не работает или слетел, это не целесообразно

**Comment by RudyWadeBoom** [comment]
@RudyWadeBoom Хорошо, скины добавляют игроку своего рода индивидуальность, это прикольно, почему бы не использовать даже костыль? Ладно, опустим, а что если использовать подгрузку скинов через лаунчер? В учётку так и так никто не сможет войти, пока не зарегисорируется на сайте, лаунчер будет проверять скин и подписывать под ник игрока и погружать на сервер, загрузку также встроить в лаунчер. Хранение сделать хз где

**Comment by RudyWadeBoom** [comment]
@NeotenySS Хорошо, скины добавляют игроку своего рода индивидуальность, это прикольно, почему бы не использовать даже костыль? Ладно, опустим, а что если использовать подгрузку скинов через лаунчер? В учётку так и так никто не сможет войти, пока не зарегисорируется на сайте, лаунчер будет проверять скин и подписывать под ник игрока и погружать на сервер, загрузку также встроить в лаунчер. Хранение сделать хз где

**Comment by NeotenySS** [comment]
@RudyWadeBoom Пф... ну в теории это возможно, тогда запрос этот не актуален, так как требование сделать на сайте.
Но если я сейчас займусь лаунчером, то он ляжет, а сервер придется приостановить (разработку) на время.
Мы можем попробовать выполнить этот запрос после открытия сервера.

**Comment by RudyWadeBoom** [comment]
@NeotenySS я заберу на себя работу по серверу полностью тогда, а ты бери лаунчер и попробуем.

**Comment by NeotenySS** [comment]
@RudyWadeBoom Ок, но нужно согласие от @KamariON-wkv на изменение заявки, иначе я её закрою и Вам нужно будет открывать по новой, но если я возьмусь за это, то сразу лаунчер ляжет и возможно будет не доступен.

**Comment by KamariON-wkv** [comment]
Даю согласие на редактирование запроса @NeotenySS

**Comment by NeotenySS** [comment]
@KamariON-wkv оперативно, думал ты ответ Вы дадите позже и обдумаете. Хорошо, попробуем сделать, лаунчер возможно не будет доступен через пару минут.
@RudyWadeBoom предупреди

**Comment by NeotenySS** [comment]
@KamariON-wkv оперативно, думал ответ Вы дадите позже и обдумаете. Хорошо, попробуем сделать, лаунчер возможно не будет доступен через пару минут.
@RudyWadeBoom предупреди

**Comment by NeotenySS** [comment]
Выполнено
