### ISSUE TITLE
[Улучшение] Режим боя 

### ISSUE THREAD

**Issue by KamariON-wkv** [NeotenySS/MineAge#3]
**Где хотите осуществить идею? (Сайт, сервер, лаунчер, донат магазин, дискорд)**
Ответ:
На сервере
**Подробное описание идеи**
Ответ:
Когда падаешь с высоты там с 3-4 блоков у тебя появляется режим боя, в режиме боя ты не можешь не строить, не ломать, не подбирать. Я предлагаю сделать так что бы режим боя появлялся после того как ты ударил игрока, а не упал с высоты.
**Ваш ник в игре и в дискорде**
Ответ:
kybik_1da
**Опишите как это может улучшить проект**
Ответ:
В основном он не улучшит сервер но сделает геймплей играбельным, да возможно он и сейчас играбельный но не приятно когда получаешь урон от падения и не можешь подобрать тот же самый уголь, или поставить блок, сломать его так же./
Очень сильно надеюсь что вы прислушайтесь к моему мнению. Благодарю! 

**!Не удалять текст ниже!**
Я оформил текст правильно и дал максимально подробную информацию. Я оставляю право за разработчиком или владельцем проекта согласиться на моё предложение или отказаться от него, в обоих случаях я не имею претензий к проекту и его руководящему составу. Я не претендую на идею в случае внедрения и отдаю права пользования проекту. В случае изменения данного текста или его удаления, разработчик или владелец проекта имеет полное право закрыть тикет без объяснения причин.

**Comment by KamariON-wkv** [comment]
Где хотите осуществить идею? (Сайт, сервер, лаунчер, донат магазин, дискорд)
Ответ:
Сервер - Лаунчер
Подробное описание идеи
Ответ:
Хотелось бы для улучшение игры на сервере иметь мод на приближение, в оптифане нажимая английскую кнопку с можно приблизить изображение, конечно на версии 1.19.4 есть подзорная труба но труба не очень удобная для использование так как закрывает пол экрана и разглядеть что то становится труднее.
Ваш ник в игре и в дискорде
Ответ:
kybik_1da
Опишите как это может улучшить проект
Ответ:
Играя на сервере иногда ты не особо понимаешь что находится в дали, в оптифайне же можно разглядеть то же самую деревню. Это моё мнение но и моих друзей не особо привычно играть без приближения изображения. Очень сильно надеюсь что вы прислушайтесь к моему мнению. Благодарю!

!Не удалять текст ниже!
Я оформил текст правильно и дал максимально подробную информацию. Я оставляю право за разработчиком или владельцем проекта согласиться на моё предложение или отказаться от него, в обоих случаях я не имею претензий к проекту и его руководящему составу. Я не претендую на идею в случае внедрения и отдаю права пользования проекту. В случае изменения данного текста или его удаления, разработчик или владелец проекта имеет полное право закрыть тикет без объяснения причин.

**Comment by NeotenySS** [comment]
@KamariON-wkv Хорошо, я посмотрю что можно будет с этим сделать.
В действительности не вижу причины вводить в режим боя игрока который упал с высоты по своей вине или ему помогли.

**Comment by NeotenySS** [comment]
Выполнено
