### ISSUE TITLE
[Улучшение] Температура тела.

### ISSUE THREAD

**Issue by KamariON-wkv** [NeotenySS/MineAge#4]
**Где хотите осуществить идею? (Сайт, сервер, лаунчер, донат магазин, дискорд)**
Ответ:
Сервер
**Подробное описание идеи**
Ответ:
Температура реализована прикольно но как по мне она слишком жесткая. К примеру когда стоишь у тебя температура тела 36 градусов тока начинаешь бежать и температура повышается до 40 градусов это смотря на то что у меня  золотая броня которая даёт -4 градуса,  а когда бежишь без брони у тебя температура тела повышается до 50 градусов иза чего начинаешь гореть.Конечно возможно это прикольно но не совсем реалистично потому что в реальной жизни к примеру от простого бега у тебя не поднимается температура тела  до 50 градусов. Поблагодарим с другом если температура будет упрощена, так как даже в пещере где по всем законам должно быть холодно все ровно у тебя 40 градусов температура тела.Добавляю то что я не был в зимней пещере.  Спасибо за внимание!
**Ваш ник в игре и в дискорде**
Ответ:
kybik_1da
**Опишите как это может улучшить проект**
Ответ:
Сервер это не улучшит но улучшит геймплей игроков.

**!Не удалять текст ниже!**
Я оформил текст правильно и дал максимально подробную информацию. Я оставляю право за разработчиком или владельцем проекта согласиться на моё предложение или отказаться от него, в обоих случаях я не имею претензий к проекту и его руководящему составу. Я не претендую на идею в случае внедрения и отдаю права пользования проекту. В случае изменения данного текста или его удаления, разработчик или владелец проекта имеет полное право закрыть тикет без объяснения причин.

**Comment by NeotenySS** [comment]
@KamariON-wkv Я слегка упрощу температуру, но лишь слегка, так как Вы не учитываете другие факторы, а именно что на температуру влияет: биом, сезон, высота блока и погода и время и вода/еда, броня, бег, лучи солнца (свет) и кучу всего другого.
Плюс ко всему остыть можно с помощью купания в воде или выпив воду/молоко.

**Comment by NeotenySS** [comment]
@KamariON-wkv 
1. Я прямо сейчас провожу тест, бегаю в биоме пустыня (самое жаркое место) + на сервере установил дату 1 июня, время 13:00, самое жаркое время, в руках ничего не держу и бегу + прыгаю, максимальная температура варьируется от 49-51 градуса и начинается возгорание. Что вполне логично в пустыне, не знаю с какими трудностями Вы там столкнулись.

2. Если стоять на месте, то вообще 45 градусов в самом жарком биоме днём.
в других биомах от 25 до 40 варьируется в режиме бег + прыжок.

3. В золотой броне в самом жарком биоме в режиме бег + прыжок температура варьируется от 41 до 45 градусов.
 
Во всех случаях беру факел в руки (который добавляет тепло телу), тогда идёт возгорание.

4. Выпил бутылку с водой и -10 градусов, то есть сейчас в режиме бег + прыжок в пустыне с надетой золотой бронёй у меня температура от 32 до 36. Даже с факелом в рукам доходит температура до 43 градусов.

5. Я спустился в этом же биоме на низкий уровень блоков и даже там моя максимальная температура в броне составила 45 градусов без бутылки воды.

Итог: Не нужно в жаркое время приближаться к теплым источникам, используйте бутылку с водой чтобы снизить температуру на 10 градусов. Думайте, чтобы уследить за своей температурой.

Что будет сделано: В данный момент эффект от выпитой воды снижает температуру на 10 градусов и эффект длиться 5 минут, и я сделаю изменение времени эффекта и оно будет действовать дольше, 15 минут вместо 5и минут. Я не буду менять температуру золотой брони.

P.S.: Эта функция с температурой добавляет сложность при выживании и нет цели копировать или эмитировать реальную жизнь в майнкрафт (ибо чтобы делать как в реальной жизни где Вы выше привели пример, то как минимум нужно мир делать не из кубиков).

Остальные правки будут внесены в соответствии с балансом с учётом жарких реалий.

**Comment by NeotenySS** [comment]
Выполнено (согласно анализа и более корректного запроса)
Читайте лог обновления
