### ISSUE TITLE
[Улучшение] Заработок монет

### ISSUE THREAD

**Issue by KamariON-wkv** [NeotenySS/MineAge#5]
**Где хотите осуществить идею? (Сайт, сервер, лаунчер, донат магазин, дискорд)**
Ответ:
На сервере
**Подробное описание идеи**
Ответ:
Добавить скупщику больше предметов для покупки там к примеру тросник, сырое мясо, морковь, пшеница, картошка, кожа, шерсть и тд. Потому что для создание города надо 500 м, а заработок идёт с руд и то не большой так же надо чтоб были деньги на казне но руда тоже нужна для развития поселения. Да и неохота постоянно добывать руды будет удобнее если бы в городе были те же самые фермеры, месняки, лесорубы и тд. Спасибо за внимание!
**Ваш ник в игре и в дискорде**
Ответ:
kybik_1da
**Опишите как это может улучшить проект**
Ответ:
Улучшит экономику сервера.

**!Не удалять текст ниже!**
Я оформил текст правильно и дал максимально подробную информацию. Я оставляю право за разработчиком или владельцем проекта согласиться на моё предложение или отказаться от него, в обоих случаях я не имею претензий к проекту и его руководящему составу. Я не претендую на идею в случае внедрения и отдаю права пользования проекту. В случае изменения данного текста или его удаления, разработчик или владелец проекта имеет полное право закрыть тикет без объяснения причин.

**Comment by NeotenySS** [comment]
@KamariON-wkv Если Вы следите за моим личным гитом, то обратите внимание на то, что:
1. Есть запрос **Продажа предметов на стартовой локации** который ещё находится в разработке.
2. У города имеется возможность добывать ресурс, достаточно провести раскопки, добыча ежедневная (24 часа реального времени).
3. Метод заработка имеется также путём захвата алтаря, есть алтарь который вознаграждает Вас за контроль в виде 500 рупий.

**Comment by NeotenySS** [comment]
Этот запрос является дублем моих запросов, которые были выполнены или находятся в стадии разработки, поэтому я закрываю Ваш запрос с пометкой выполнено.
